### ISSUE TITLE
不会震动了吗？

### ISSUE THREAD

**Issue by J3n5en** [GSWXXN/UnlockMIUICameraSnap#10]
没有震动以为没生效，折腾半天打开相册一堆照片哈哈哈。
怎么开启震动呢？不然不知道拍没拍到。

机型: mix fold3
系统: hyperos 
相机版本: 5.1.000600.2
模块版本:1.5

模块日志:
----part 2 start----
[ 2023-12-12T04:01:17.592    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][I][com.android.camera] load members from prefs
[ 2023-12-12T04:01:17.598    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][I][com.android.camera] load obfuscated members in com.android.camera cost 11ms
[ 2023-12-12T04:01:17.605    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public void d.d.a.k7.d$a.run()], this will be ignored
[ 2023-12-12T04:01:17.611    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public static android.app.PendingIntent android.app.PendingIntent.getActivity(android.content.Context,int,android.content.Intent,int)], this will be ignored
[ 2023-12-12T04:01:17.616    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [private void d.d.a.k7.c.t()], this will be ignored
[ 2023-12-12T04:01:17.621    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [private void d.d.a.k7.c.y()], this will be ignored
[ 2023-12-12T04:01:17.626    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public synchronized void d.d.a.k7.c.A()], this will be ignored
[ 2023-12-12T04:01:17.631    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public boolean d.k.a.b.P8()], this will be ignored
[ 2023-12-12T04:01:17.635    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public static java.lang.String d.d.a.t3.J0(java.lang.String)], this will be ignored
[ 2023-12-12T04:01:17.641    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public void com.android.camera.fragment.settings.BasePreferenceFragment.Me()], this will be ignored
[ 2023-12-12T04:01:17.647    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] Already Hooked Member [public boolean com.android.camera.fragment.settings.CameraPreferenceFragment.onPreferenceChange(androidx.preference.Preference,java.lang.Object)], this will be ignored
[ 2023-12-12T04:01:17.677     1000:  4202:  7772 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][I][android] allow android.permission.FOREGROUND_SERVICE privilege
[ 2023-12-12T04:01:20.019    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][W][com.android.camera] stopCamcorder: release
[ 2023-12-12T04:01:20.022    10133: 11681: 11681 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][D][com.android.camera] stopCamcorder: mMediaRecorder is null

**Comment by GSWXXN** [comment]
会震动的，之前也有人反馈过没震动提示，后来发现是因为同时使用了一个桌面动画补全的模块，那里面有震动重映射，可能是和这种类似的功能有冲突，你自己排查一下？

**Comment by J3n5en** [comment]
不行，我把其他所有xposed都关了，也不震动

**Comment by GSWXXN** [comment]
你把你的相机提取出来发给我一下吧

**Comment by J3n5en** [comment]
https://j3n5en-my.sharepoint.com/:u:/p/admin/Ebf9UfEHUrRMrZp7V7Azsh4BOxR3ICgCO6_5M2llwLKnSA?e=WJThHS
谢谢！

**Comment by GSWXXN** [comment]
我安装你的相机提取包了, 测试下来震动并没有什么问题, 我之前说的那个模块并不是 Xposed模块, 而是某个面具模块, 你再试试排查一下?

**Comment by J3n5en** [comment]
面具只留lsposed，xposed里面只留这个模块也不行，估计是系统有啥冲突吧，我这别人的官改，不管了一样用，谢谢你
