### ISSUE TITLE
小米15 Pro无法使用

### ISSUE THREAD

**Issue by HuiNIMA** [GSWXXN/UnlockMIUICameraSnap#15]
机型：小米15 Pro
系统版本：2.0.17.0.VOBCNXM(Android 15)
相机版本：5.4.000510.3
https://www.123684.com/s/GJBmjv-20Z0A?提取码：SCaN
问题描述：安装后相机app以及lsp管理器中都没有出现街拍选项，熄屏长按音量-键无反应

**Comment by GSWXXN** [comment]
在过去版本的相机里, 虽然 MIUI 在部分机型上移除了原街拍模式的开关, 但相关代码逻辑始终有大量的保留. 这个模块借助保留的代码才得以实现. 从你发给我的相机版本来看, 这次 HyperOS 将原街拍代码移除得很干净, 我几乎找不到原来的任何实现逻辑. 所以如果还要实现街拍模式, 模块就要全部推倒重写, 需要模块自行实现街拍模式的全部逻辑. 但我现在没有太多的时间和精力, 这个项目可能会暂时搁置在这里了
