### ISSUE TITLE
小米13Ultra 有问题，相机闪退，相机版本：5.0.000710.0

### ISSUE THREAD

**Issue by nodis** [GSWXXN/UnlockMIUICameraSnap#6]
大佬，小米13Ultra 有问题，相机闪退，相机版本：5.0.000710.0

错误代码如下：
Build fingerprint: 'Xiaomi/ishtar/ishtar:13/TKQ1.221114.001/V14.0.23.6.26.DEV:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-07-12 18:45:59.773825312+0800
Process uptime: 2s
Cmdline: com.android.camera
pid: 10918, tid: 11009, name: pool-8-thread-1  >>> com.android.camera <<<
uid: 10128
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_object == null
    in call to MonitorEnter
    from boolean org.lsposed.lspd.nativebridge.HookBridge.hookMethod(java.lang.reflect.Executable, java.lang.Class, int, java.lang.Object)'
    x0  0000000000000000  x1  0000000000002b01  x2  0000000000000006  x3  0000007941527df0
    x4  382f2f30301f1f37  x5  382f2f30301f1f37  x6  382f2f30301f1f37  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007a66671cb0  x10 0000000000000001  x11 0000007a666e67c8
    x12 000000799ac47430  x13 000000000085ef38  x14 000000000085edf8  x15 0000007a66675982
    x16 0000007a66751a80  x17 0000007a6672a450  x18 000000793c826000  x19 0000000000002aa6
    x20 0000000000002b01  x21 00000000ffffffff  x22 000000000000006e  x23 0000007941528008
    x24 00000079c4816000  x25 0000007941528000  x26 0000007941529000  x27 00000079c460af90
    x28 00000079c460b1c0  x29 0000007941527e70
    lr  0000007a666d7748  sp  0000007941527dd0  pc  0000007a666d7774  pst 0000000000001000
backtrace:
      #00 pc 000000000008d774  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 449f781894033dce6346794a1ee593e0)
      #01 pc 00000000006221ec  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1204) (BuildId: 53aea03d478a82db6c483ee54c0d91e3)
      #02 pc 0000000000017114  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+84) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
      #03 pc 0000000000016648  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+356) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
      #04 pc 000000000045c6c4  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2368) (BuildId: 53aea03d478a82db6c483ee54c0d91e3)
      #05 pc 00000000004c2800  /apex/com.android.art/lib64/libart.so (art::JNI<false>::MonitorEnter(_JNIEnv*, _jobject*)+1380) (BuildId: 53aea03d478a82db6c483ee54c0d91e3)
      #06 pc 0000000000013c18  /memfd:jit-cache (deleted)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/ishtar/ishtar:13/TKQ1.221114.001/V14.0.23.6.26.DEV:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-07-12 18:45:59.773825312+0800
Process uptime: 2s
Cmdline: com.android.camera
pid: 10918, tid: 11009, name: pool-8-thread-1  >>> com.android.camera <<<
uid: 10128
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_object == null
    in call to MonitorEnter
    from boolean org.lsposed.lspd.nativebridge.HookBridge.hookMethod(java.lang.reflect.Executable, java.lang.Class, int, java.lang.Object)'
    x0  0000000000000000  x1  0000000000002b01  x2  0000000000000006  x3  0000007941527df0
    x4  382f2f30301f1f37  x5  382f2f30301f1f37  x6  382f2f30301f1f37  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  0000007a66671cb0  x10 0000000000000001  x11 0000007a666e67c8
    x12 000000799ac47430  x13 000000000085ef38  x14 000000000085edf8  x15 0000007a66675982
    x16 0000007a66751a80  x17 0000007a6672a450  x18 000000793c826000  x19 0000000000002aa6
    x20 0000000000002b01  x21 00000000ffffffff  x22 000000000000006e  x23 0000007941528008
    x24 00000079c4816000  x25 0000007941528000  x26 0000007941529000  x27 00000079c460af90
    x28 00000079c460b1c0  x29 0000007941527e70
    lr  0000007a666d7748  sp  0000007941527dd0  pc  0000007a666d7774  pst 0000000000001000
backtrace:
      #00 pc 000000000008d774  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 449f781894033dce6346794a1ee593e0)
      #01 pc 00000000006221ec  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1204) (BuildId: 53aea03d478a82db6c483ee54c0d91e3)
      #02 pc 0000000000017114  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+84) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
      #03 pc 0000000000016648  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+356) (BuildId: ef369bfbad96b532c6d8e0b144a68b96)
      #04 pc 000000000045c6c4  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2368) (BuildId: 53aea03d478a82db6c483ee54c0d91e3)
      #05 pc 00000000004c2800  /apex/com.android.art/lib64/libart.so (art::JNI<false>::MonitorEnter(_JNIEnv*, _jobject*)+1380) (BuildId: 53aea03d478a82db6c483ee54c0d91e3)
      #06 pc 0000000000013c18  /memfd:jit-cache (deleted)

**Comment by GSWXXN** [comment]
这与[ v1.3 更新日志](https://github.com/Xposed-Modules-Repo/com.gswxxn.camerasnap/releases/tag/1300-1.3) 中所提及的问题是相同的
