### ISSUE TITLE
Android 14无法使用

### ISSUE THREAD

**Issue by ssrubsd** [GSWXXN/UnlockMIUICameraSnap#8]
MIUI版本 14.0.3 
相机版本 5.1.000240.1

**Comment by ssrubsd** [comment]
[modules_1970-01-02T02_11_04.480693.log](https://github.com/GSWXXN/UnlockMIUICameraSnap/files/13246943/modules_1970-01-02T02_11_04.480693.log)

**Comment by GSWXXN** [comment]
可以把你的相机提取出来发给我嘛

**Comment by ssrubsd** [comment]
> 可以把你的相机提取出来发给我嘛

pan.baidu.com/s/1WJnm_UKMjFPlUcH3K7OWMQ?pwd=ejqu

**Comment by GSWXXN** [comment]
请测试一下这个版本 
[UnlockMIUICameraSnap_1.4-Preview.1(1301).apk](https://pub-79de9e4e50b74580bb8f0950d7ce0ece.r2.dev/UnlockMIUICameraSnap_1.4-Preview.1(1301).apk)

**Comment by ssrubsd** [comment]
还是不行，在LSPosed把系统框架勾选上也尝试过了
[modules_1970-01-01T22_35_05.790724.log](https://github.com/GSWXXN/UnlockMIUICameraSnap/files/13256027/modules_1970-01-01T22_35_05.790724.log)

**Comment by GSWXXN** [comment]
我在你发的日志里并没有发现有关我这个模块的异常，麻烦请你具体描述一下你对这个模块的预期
另外，在你日志里提到发出异常的模块是 CustomCamera，这个模块似乎已停更很长时间，而且不适配近年的相机，建议移除

**Comment by GSWXXN** [comment]
另外目前模块仅作用在相机上，无需勾选系统框架

**Comment by ssrubsd** [comment]
就是模块无效不能用，息屏状态按音量下键没有任何反应，也试过把其他模块都关了还是不行

**Comment by GSWXXN** [comment]
在相机设置里检查一下街拍模式选项是否为关闭状态，模块在息屏下触发的条件是长按音量减不松手

**Comment by ssrubsd** [comment]
这些都设置了，root权限也给了，自启动也设置了，可它就是无反应，然后也清空过相机的数据，还是a13的时候使用一切正常

**Comment by GSWXXN** [comment]
我在我的设备 (Android 13) 上实装过你给我发的这个版本的相机，我没有发现模块在这上面运行出现问题。由于我的设备现在还没有机会可以升级到 Android 14, 所以测试环境不能和你保持一致，如果真的是因为安卓版本导致的问题，那么短时间内我可能无法修复

或许你可以把 LSPosed 的完整 zip 包日志发给我一下？我看看在 zip 包内其他位置有没有明显的报错信息

**Comment by ssrubsd** [comment]
[LSPosed_2023-11-04T20_06_36.618855.zip](https://github.com/GSWXXN/UnlockMIUICameraSnap/files/13256606/LSPosed_2023-11-04T20_06_36.618855.zip)
谢谢了

**Comment by GSWXXN** [comment]
看不出来什么，现在猜测 miui 把息屏对长按音量减的事件给屏蔽了，这部分是在系统框架中实现的，如果要将这部分补回来的话，可能需要大量的试错，我的设备都没有能升级到A14的，所以要搁置一段时间了

**Comment by ssrubsd** [comment]
> 看不出来什么，现在猜测 miui 把息屏对长按音量减的事件给屏蔽了，这部分是在系统框架中实现的，如果要将这部分补回来的话，可能需要大量的试错，我的设备都没有能升级到A14的，所以要搁置一段时间了

那也没办法了，静候大佬佳音吧

**Comment by GSWXXN** [comment]
我已升级到 HyperOS, 发现在系统框架中确实移除了对街拍模式的处理, 现在我尝试将其加回, 请测试下面的版本, 记得在作用域中勾选系统框架
[UnlockMIUICameraSnap_1.4-Preview.2(1301).apk](https://pub-79de9e4e50b74580bb8f0950d7ce0ece.r2.dev/UnlockMIUICameraSnap_1.4-Preview.2(1301).apk)

**Comment by ssrubsd** [comment]
> 我已升级到 HyperOS, 发现在系统框架中确实移除了对街拍模式的处理, 现在我尝试将其加回, 请测试下面的版本, 记得在作用域中勾选系统框架 [UnlockMIUICameraSnap_1.4-Preview.2(1301).apk](https://pub-79de9e4e50b74580bb8f0950d7ce0ece.r2.dev/UnlockMIUICameraSnap_1.4-Preview.2(1301).apk)

实测可用！版本14.0.5
