### ISSUE TITLE
小米12s ultra 相机5.1.000600.1无法使用

### ISSUE THREAD

**Issue by xiaofeifeibufei** [GSWXXN/UnlockMIUICameraSnap#9]
小米12s ultra 相机5.1.000600.1无法使用
1.0.23.12.4.DEV 版本
LSPOSED 安装1.4 unlock版本
勾选系统框架和相机。
息屏长按音量下键无效。

没有地方进行设置？

**Comment by GSWXXN** [comment]
![Screenshot_2023-12-10-23-26-02-818_com.android.camera.jpg](https://github.com/GSWXXN/UnlockMIUICameraSnap/assets/34705923/a00fa588-d4a9-4b7a-8a17-91f3b999c2d4)

在相机设置里找选项，我是的设备和你是相同型号，相同相机版本，使用上没有问题的

**Comment by xiaofeifeibufei** [comment]
相机设置里面出不来这个入口。蛋疼。重启好几次了。。

**Comment by GSWXXN** [comment]
那把你的lsp日志提取出来发给我一下呗

**Comment by xiaofeifeibufei** [comment]
我把核心破解，woobox for miui 这2个模块取消勾选，重启正常了。 怀疑是模块的冲突。 谢谢大佬。
